trigger:
- master

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'Ubuntu-16.04'
    continueOnError: true
    steps:
    - script: echo "hello to my first Build"
    - task: DotNetCoreCLI@2
      inputs:
        command: restore
        projects: '**/*.csproj'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        workingDirectory: 'www'
    - task: DotNetCoreCLI@2
      inputs:
        command: publish
        publishWebProjects: True
        arguments: '--output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: True

# this code takes all the files in $(Build.ArtifactStagingDirectory) and uploads them as an artifact of your build.
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
        artifactName: 'devops-demo'

- stage: Deploy
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'Ubuntu-16.04'
    environment: 'Prod'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo "hello, Deploy!!!"
          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'jm-devops-demo - 1 - Azure'
              appType: 'webApp'
              appName: 'jm-devops-demo'
              package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
              deploymentMethod: 'auto'