trigger:
- master

variables:
  # Azure service connection established during pipeline creation
  azureSubscription: jmutchek-internal
  appName: jm-api-demo
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

- task: AzureFunctionApp@1 # Add this at the end of your file
  inputs:
    azureSubscription: jm-devops-demo - 1 - Azure
    appType: functionApp
    appName: $(appName)
    package: $(System.ArtifactsDirectory)/**/*.zip
