trigger: master

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'Ubuntu-16.04'
    continueOnError: true
    steps:
    - script: echo "hello to my first Build"

- stage: Deploy
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'Ubuntu-16.04'
    environment: 'Prod'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo "hello, Deploy!!!"
          - task: DotNetCoreCLI@2
            inputs:
                command: 'build'
                projects: '*.csproj'
                workingDirectory: 'www'